# Generated by Django 4.2 on 2026-01-05 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.classe')),
            ],
        ),
    ]
