# Generated by Django 4.2 on 2026-01-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_classe_name_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='Topic',
        ),
    ]
