# Generated by Django 4.2 on 2026-01-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_rename_topic_topic_class_rename_name_topic_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Topic',
            new_name='topic',
        ),
    ]
