# Generated by Django 4.2 on 2026-01-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_rename_topic_topic_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Class',
            new_name='classe',
        ),
    ]
