# Generated by Django 4.2 on 2026-01-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_rename_class_topic_classe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='title',
        ),
    ]
