# Generated by Django 4.2 on 2026-01-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_rename_topic_topic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
