# Generated by Django 4.2 on 2026-01-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_topic_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Status',
            new_name='is_completed',
        ),
    ]
