# Generated by Django 4.2 on 2026-01-07 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_copy_classe_to_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='classe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Accounts.classe'),
            preserve_default=False,
        ),
    ]
