# Generated by Django 4.2 on 2026-01-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_alter_topic_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classe',
        ),
    ]
