# Generated by Django 4.2 on 2026-01-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0019_copy_classe_to_classes_again'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classe',
        ),
    ]
