# Generated by Django 4.2 on 2026-01-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_remove_student_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
    ]
