# Generated by Django 4.2 on 2026-01-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0021_remove_student_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='students_m2m', to='Accounts.classe'),
        ),
    ]
